[[redirects]]
  # Routes all requests (which are not static files) to the function handler.
  from = "/*"
  to = "/.netlify/functions/index/:splat"
  status = 200
  force = true

functionsDirectoryOrigin = "ui"
plugins = []
headers = []
redirects = []

[functions]
  [functions."*"]

[build]
publish = "dist"
publishOrigin = "default"
commandOrigin = "ui"
# CRITICAL FIX 1: Removed global install.
command = "npm ci && npm run prisma:generate && npm run prisma:migrate:deploy && npm run build"
# CRITICAL FIX 2: Point to the compiled JS entry file (relative to root).
functions = "dist/index.js"

  [build.environment]
    NODE_ENV = "production"

  [build.processing]
    [build.processing.css]
    [build.processing.html]
    [build.processing.images]
    [build.processing.js]

  [build.services]
