functionsDirectoryOrigin = "ui"
plugins = []
headers = []
redirects = []

[functions]
  [functions."*"]

[build]
publish = "dist"
publishOrigin = "default"
commandOrigin = "ui"
# CRITICAL FIX: Removed the unstable global install command.
command = "npm ci && npm run prisma:generate && npm run prisma:migrate:deploy && npm run build"
functions = "dist"

  [build.environment]
    NODE_ENV = "production"

  [build.processing]
    [build.processing.css]
    [build.processing.html]
    [build.processing.images]
    [build.processing.js]

  [build.services]
