functionsDirectoryOrigin = "ui"
plugins = []
headers = []
redirects = []

[functions]
  [functions."*"]

[build]
publish = "dist"
publishOrigin = "default"
commandOrigin = "ui"
command = "npm ci && npm install -g @nestjs/cli && npm run prisma:generate && npm run prisma:migrate:deploy && npm run build"

functions = "node dist/src/index"

  [build.environment]
    NODE_ENV = "production"

  [build.processing]
    [build.processing.css]
    [build.processing.html]
    [build.processing.images]
    [build.processing.js]

  [build.services]
