[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index/:splat"
  status = 200
  force = true

functionsDirectoryOrigin = "ui"
plugins = []
headers = []
redirects = []

[functions]
  [functions."*"]

[build]
publish = "dist"
publishOrigin = "default"
commandOrigin = "ui"
# FINAL FIX: Explicitly install the NestJS CLI locally before the build step.
command = "npm ci && npm run prisma:generate && npm run prisma:migrate:deploy && npm install -g @nestjs/cli && npm run build"
functions = "/opt/build/repo/dist/index"

  [build.environment]
    NODE_ENV = "production"

  [build.processing]
    [build.processing.css]
    [build.processing.html]
    [build.processing.images]
    [build.processing.js]
  [build.services]
