[build]
  publish = "dist"                         # dummy folder since backend-only
  functions = "dist"                       # points to compiled index.serverless.js
  command = "npm ci && npm run prisma:generate && npm run build"

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index.serverless"
  status = 200
  force = true
